import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Swiper, SwiperSlide } from 'swiper/react';
import 'swiper/css';

import heydayLogo from '../public/logo.png'
import formImage from '../public/FormImage.png'
import image1 from '../public/image-1.png'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>First Time Facial</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
          <Image 
            className={styles.logo}
            src={heydayLogo}
            alt="Heyday Skincare logo"
            height={50}
            width={100}
          />
      </header>
      <main className={styles.main}>
        <section className={styles.hero}>
          <div className={styles.heroImageContainer}>
            <Image 
              priority
              src={formImage}
              alt="Woman receiving facial treatment"
              layout="fill"
              objectFit='cover'
            />
          </div>
          <div className={styles.formContainer}>
            <h1>Sign up to Enjoy Your First Facial for $70</h1>
            <p>Unlock this exclusive offer(with over 50% in savings!) & get ready to glow.</p>
            <form className={styles.form}>
              <input type="text" className={styles.input} placeholder='First Name*'/>
              <input type="text" className={styles.input} placeholder='Last Name*'/>
              <input type="text" className={styles.input} placeholder='Email*'/>
              <input type="text" className={styles.input} placeholder='Phone Number'/>
              <input type="text" className={styles.input} placeholder='Zip Code'/>
              <div>
                <input type="submit" value="Book Your Facial" className={styles.button}/>
              </div>
            </form>
          </div>
        </section>
        <section className={styles.imageGrid}>
          <div>
            <h1>Our Facial, The Heyday Way</h1>
            <p>Up front, we keep our menu simple—behind the scenes, our estheticians are handcrafting a cocktail of ingredients to meet your skin’s unique needs and goals.</p>
          </div>
          <div>
            <Swiper
              pagination
            >
              <SwiperSlide>
                <div className={styles.slideImage}>
                  <Image 
                    src={image1}
                    layout="responsive"
                  />
                </div>
                <h2>Talk to us about your goals.</h2>
              </SwiperSlide>
              <SwiperSlide>
                <div className={styles.slideImage}>
                  <Image 
                    src={image1}
                    layout="responsive"
                  />
                </div>
                <h2>Receive an expert skin analysis.</h2>
              </SwiperSlide>
              <SwiperSlide>
                <div className={styles.slideImage}>
                  <Image 
                    src={image1}
                    layout="responsive"
                  />
                </div>
                <h2>Enjoy a personalized skincare treatment.</h2>
              </SwiperSlide>
              <SwiperSlide>
                <div className={styles.slideImage}>
                  <Image 
                    src={image1}
                    layout="responsive"
                  />
                </div>
                <h2>Learn how to enhance your daily routine.</h2>
              </SwiperSlide>
            </Swiper>
          </div>
        </section>
      </main>
      <footer>
          <div className={styles.footer}>
            <h2>Ready to live your Heyday every day?</h2>
            <button className={styles.button}>Take 50% Off Your First Facial</button>
          </div>
        </footer>
    </div>
  )
}

